name: .NET CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') == false && contains(github.event.head_commit.message, '[no ci]') == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: nuget restore

      - name: Build
        run: Start-Process "build.bat" "windows --override-custom-files" -Wait -NoNewWindow

  publish:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: Start-Process "build.bat" "windows --override-custom-files" -Wait -NoNewWindow

      - name: Remove unnecessary files
        run: |
          Remove-Item .\.build\modules\ -Recurse
          
      - name: Download Tnms Library files from GitHub latest release
        run: |
        Invoke-WebRequest https://github.com/fltuna/TnmsAdministrationPlatform/releases/latest/download/TnmsAdministrationPlatform.zip -OutFile TnmsAdministrationPlatform.zip
        Invoke-WebRequest https://github.com/fltuna/TnmsExtendableTargeting/releases/latest/download/TnmsExtendableTargeting.zip -OutFile TnmsExtendableTargeting.zip
        Invoke-WebRequest https://github.com/fltuna/TnmsLocalizationPlatform/releases/latest/download/TnmsLocalizationPlatform.zip -OutFile TnmsLocalizationPlatform.zip
        
      - name: Extract Tnms Library files
        run: |
        Expand-Archive -Path TnmsAdministrationPlatform.zip -DestinationPath .\.build\
        Expand-Archive -Path TnmsExtendableTargeting.zip -DestinationPath .\.build\
        Expand-Archive -Path TnmsLocalizationPlatform.zip -DestinationPath .\.build\

      - name: Compress artifacts
        run:
          Compress-Archive -Path .build/* -Destination TnmsPluginFoundation.zip

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: TnmsPluginFoundation.zip

  release:
    runs-on: windows-latest
    needs: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/

      - name: check files
        run : |
          tree

      - name: Create Release and Upload Asset
        run: |
          gh release create "${{ github.ref_name }}" --title "Release ${{ github.ref_name }}" --generate-notes --draft=false artifacts/TnmsPluginFoundation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
  publish-nuget:
    runs-on: windows-latest
    needs: release

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore
        working-directory: TnmsPluginFoundation

      - name: Build
        run: dotnet build -c Release -p:DebugType=None -p:DebugSymbols=false
        working-directory: TnmsPluginFoundation

      - name: Pack
        run: dotnet pack --configuration Release
        working-directory: TnmsPluginFoundation

      - name: Extract version
        id: package_version
        run: |
          $xml = [Xml] (Get-Content TnmsPluginFoundation/TnmsPluginFoundation.csproj)
          $version = $xml.Project.PropertyGroup.PackageVersion
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Publish to Nuget
        run: |
          dotnet nuget push "bin/Release/TnmsPluginFoundation.${{env.VERSION}}.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
        working-directory: TnmsPluginFoundation